CLASS test_class_shubham2_renamed DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS printHello.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS test_class_shubham2_renamed IMPLEMENTATION.
  METHOD printhello.
    WRITE 'hello'.
  ENDMETHOD.

ENDCLASS.
