CLASS test_class_shubham DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS printHello.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS TEST_CLASS_SHUBHAM IMPLEMENTATION.


  METHOD printhello.
    WRITE 'Hello'. " edited in ADT
    WRITE 'World'.
    WRITE 'In GUI'. " edited again
  ENDMETHOD.
ENDCLASS.
